openapi: 3.0.3
info:
  title: E-financing
  description: >
    The E-financement API is used **to initiate and manage a E-financement

    subscription** from the checkout page on behalf of the buyer.



    According **the solution code** your demand will be issued at the producer

    side.



    You will obtain **a redirect Url or a Html page to the producer

    E-financement customer journey**.



    At any time you can **retrieve the status and details** of your

    E-financement susbcriptions.



    Once your susbscription request is accepted by financing institution, you
    can request for a full or partial cancellation request. According, your
    subscription kind (solution code) you would have to notify the financing
    instution of, first the delivery of goods, and second the return of delivery
    before any concellation request.


    **Changelog** :

      - Remove merchantId and clientId from the response of the endpoint GET /subscriptions/{subscriptionId} because this data must not be retrieved by consumer.
      - Evolution of the response of GET /v1/subscriptions  with new fields: consolidatedSubstatus, isDelivered, isReturned.
      - Evolution of the response of GET /v1/subscriptions/{subscriptionId} with the new field consolidatedSubstatus.
  version: 1.5.2
  contact:
    name: SG ECommerce Support Team
    email: sg-ecommerce-support.world@socgen.com
    url: ''
  x-sg-name: e-financing
  x-irt-code: A8821
  x-trigram-code: BAX
  x-api-audience: PUBLIC
  termsOfService: |
    24x7
servers:
  - url: >-
      https://api.scalexpert.uatc.societegenerale.com/baas/uatc/e-financing/api/v1
tags:
  - name: Eligibility
  - name: Solution simulations
  - name: Subscriptions
  - name: Delivery
  - name: Cancellation
paths:
  /subscriptions:
    get:
      tags:
        - Subscriptions
      summary: Retrieve a list of E-Financing subscriptions
      description: |-
        You can list all **your subscriptions** by specifying **a reference**
                such as an order id or a basket id.
                        the response will contain subscription Id, dates, times, status, your references, amount financed ...
                        <br />**Main use case:** Use this API to retrieve status a credit subscription by refering an order Id or a basket Id. 
                        <br />**Important:** The list is paginated 
      externalDocs:
        description: List of error codes.
        url: >-
          https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/api-reference/e-financing-api/e-financing-error-codes
      operationId: retrieveCreditSubscriptionForSpecificMerchant
      parameters:
        - name: merchantGlobalOrderId
          in: query
          required: false
          schema:
            type: string
            description: >-
              ID of the order as a whole - as long as the items are not
              dispatched separately, with different orders ID.
            example: 340005489
        - name: merchantBasketId
          in: query
          required: false
          schema:
            type: string
            description: >-
              ID of the basket of the current transaction, as given by the
              merchant (thirdparty)
            example: 185462145
        - name: page
          in: query
          required: false
          schema:
            type: integer
            description: The page number
            format: int32
            example: 1
            default: 1
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            description: The number of elements per page
            format: int32
            example: 20
            default: 20
      responses:
        '200':
          description: List of credit subscriptions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginationCreditSubscriptionsDtoResponse'
        '401':
          description: Unauthorized. You must first authenticate to get a token.
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Missed scope or insufficient permission
          content:
            application/json: {}
        default:
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaasExceptionHttpResponse'
              examples:
                Get Internal Server Error:
                  summary: Get Internal Server Error
                  description: Get Internal Server Error
                  value:
                    timestamp: '2022-07-28T22:25:51.000Z'
                    httpStatusCode: '500'
                    httpStatusMessage: Internal Server Error
                    errorMessage: Une erreur est survenue
                    requestMethod: POST
                    requestURI: /v1/subscriptions
    post:
      tags:
        - Subscriptions
      summary: Initiate a E-Financing subscription at the E-Financing producer side
      description: >-
        **To initiate an E-Financing subscription** you will have to collect
        from your users (some will com from the checkout journey and other from
        your buyer's profile) the requested parameters including the following :

        - identity,

        - address of the buyer,

        - amount to be financed,

        - payment choosen (product code),

        - basket items details 

        - ...


        (You'll later be able to refer your E-Financing subsription with either
        your **order id** or **basket id**.) 


        Upon successful completion you will receive a json with : 

        - a **subscription Id**

        - a **redirect URL** (managed by the lender) so your customer can
        proceed with its application journey 


        **Important**


        In the request body the **solutionCode** is 1-to-1 mapped to the lenders
        and their offers. This means the two following information are key for
        you to choose the correct solutionCode :

        - the buyer's financement type choosed on the checkout page 

        - the buyer's location : France or Germmany *(more markets to come..)* 


        The detail of solutions codes used are here : 

        https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/use-cases/credit#e-financing-solution-codes
      externalDocs:
        description: List of error codes.
        url: >-
          https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/api-reference/e-financing-api/e-financing-error-codes
      operationId: initiateCreditSubscription
      parameters:
        - name: language
          in: query
          required: true
          schema:
            type: string
            description: >-
              Requested language of the UI to be used for the application
              journey on the lender website. **de-DE** for a HB credit
              subscriptions (with solution codes starts with SCDELT) and
              **fr-FR** for FF credit subscriptions (solution codes start with
              SCFR..).
            example: de-DE
      requestBody:
        description: E-Financing subscription request
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InitiateCreditSubscriptionRequest'
        required: true
      responses:
        '201':
          description: Initiate an E-Financing subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InitiateCreditSubscriptionResponse'
        '401':
          description: Unauthorized. You must first authenticate to get a token.
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Missed scope or insufficient permission
          content:
            application/json: {}
        default:
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaasExceptionHttpResponse'
              examples:
                Get Internal Server Error:
                  summary: Get Internal Server Error
                  description: Get Internal Server Error
                  value:
                    timestamp: '2022-07-28T22:25:51.000Z'
                    httpStatusCode: '500'
                    httpStatusMessage: Internal Server Error
                    errorMessage: Une erreur est survenue
                    requestMethod: POST
                    requestURI: /v1/subscriptions
  '/subscriptions/{creditSubscriptionId}/_confirmDelivery':
    post:
      tags:
        - Delivery
      summary: Confirm delivery of the items related to a specific creditSubscriptionId
      description: >-
        Confirm delivery of the items related to a specific
        creditSubscriptionId. Needed for long term credits only
      externalDocs:
        description: List of error codes.
        url: >-
          https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/api-reference/e-financing-api/e-financing-error-codes
      operationId: doConfirmDelivery
      parameters:
        - name: creditSubscriptionId
          in: path
          required: true
          schema:
            type: string
            description: The unique E-financement Subscription Id
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmDeliveryRequest'
        required: true
      responses:
        '204':
          description: request accepted but not processed (short term credit)
          content:
            application/json:
              schema:
                type: object
        '401':
          description: Unauthorized. You must first authenticate to get a token.
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Missed scope or insufficient permission
          content:
            application/json: {}
        default:
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaasExceptionHttpResponse'
              examples:
                Get Internal Server Error:
                  summary: Get Internal Server Error
                  description: Get Internal Server Error
                  value:
                    timestamp: '2022-07-28T22:25:51.000Z'
                    httpStatusCode: '500'
                    httpStatusMessage: Internal Server Error
                    errorMessage: Une erreur est survenue
                    requestMethod: POST
                    requestURI: /v1/subscriptions
  '/subscriptions/{creditSubscriptionId}/_cancel':
    post:
      tags:
        - Cancellation
      summary: Request for a cancellation for a specific E-Financing subscription
      description: >-
        Request for a cancellation request for a specific E-Financing
        subscription. Your request is different according the subscription kind
        (solution code)
      externalDocs:
        description: List of error codes.
        url: >-
          https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/api-reference/e-financing-api/e-financing-error-codes
      operationId: cancelCreditSubscription
      parameters:
        - name: creditSubscriptionId
          in: path
          required: true
          schema:
            type: string
            description: The unique Credit Subscription Id
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreditCancellationDTO'
        required: true
      responses:
        '200':
          description: Credit cancellation confirmation response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditCancellationResponse'
        '400':
          description: >-
            Bad request, The amount to cancel is more than the financedAmount.
            You can only demand for a cancellation with cancelledAmount equal or
            lower than financedAmount.
          content:
            '*/*':
              schema:
                type: object
        '401':
          description: Unauthorized. You must first authenticate to get a valid token.
          content:
            '*/*':
              schema:
                type: object
        '403':
          description: Scope missing or insufficient permissions.
          content:
            application/json: {}
        '404':
          description: The parameter creditSubscriptionId is unknown
          content:
            application/json: {}
        default:
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaasExceptionHttpResponse'
              examples:
                Get Internal Server Error:
                  summary: Get Internal Server Error
                  description: Get Internal Server Error
                  value:
                    timestamp: '2022-07-28T22:25:51.000Z'
                    httpStatusCode: '500'
                    httpStatusMessage: Internal Server Error
                    errorMessage: Une erreur est survenue
                    requestMethod: POST
                    requestURI: /v1/subscriptions
  /_simulate-solutions:
    post:
      tags:
        - Solution simulations
      summary: Calculate the simulation of the eligible e-financing solutions
      description: >-
        - Calculate the simulation of the eligible e-financing solutions

        - If solutionCodes are not specified in the request, all eligible
        e-financing solutions will be simulated.

        - The response returns an empty solutionSimulations array if there is no
        eligible e-financing solution or all the rquested solutions are not
        eligible.
      externalDocs:
        description: List of error codes.
        url: >-
          https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/api-reference/e-financing-api/e-financing-error-codes
      operationId: creditSimulation
      requestBody:
        description: The request body to simulate the eligible e-fiancing solutions.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SolutionSimulationRequest'
            examples:
              Simulation for the solution SCFRSP-3XTS.:
                description: Simulation for the solution SCFRSP-3XT.
                value:
                  financedAmount: 1500
                  buyerBillingCountry: FR
                  solutionCodes:
                    - SCFRSP-3XTS
              Simulation for the solution SCFRLT-TXNO.:
                description: Simulation for the solution SCFRLT-TXNO.
                value:
                  financedAmount: 3000
                  buyerBillingCountry: FR
                  solutionCodes:
                    - SCFRLT-TXNO
        required: true
      responses:
        '200':
          description: >-
            The result of the simulation of eligible financial solutions for a
            given amount and solution codes.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolutionSimulationResponse'
              examples:
                Simulation for the solution SCFRSP-3XTS.:
                  description: Simulation for the solution SCFRSP-3XT.
                  value:
                    financedAmount: 1500
                    buyerBillingCountry: FR
                    solutionSimulations:
                      - solutionCode: SCFRSP-3XTS
                        simulations:
                          duration: 3
                          effectiveAnnualPercentageRate: 0
                          nominalPercentageRate: 0
                          totalCost: 0
                          dueTotalAmount: 1500
                          feesAmount: 0
                          intallments:
                            - number: 1
                              amount: 500
                            - number: 2
                              amount: 500
                            - number: 3
                              amount: 500
                Simulation for the solution SCFRLT-TXNO.:
                  description: Simulation for the solution SCFRLT-TXNO.
                  value:
                    financedAmount: 3000
                    buyerBillingCountry: FR
                    solutionSimulations:
                      - solutionCode: SCFRLT-TXNO
                        simulations:
                          - duration: 12
                            effectiveAnnualPercentageRate: 8.9
                            nominalPercentageRate: 8.56
                            totalCost: 140.88
                            dueTotalAmount: 3140.88
                            feesAmount: 0
                            intallments:
                              - number: 1
                                amount: 261.74
                          - duration: 18
                            effectiveAnnualPercentageRate: 8.9
                            nominalPercentageRate: 8.56
                            totalCost: 207.24
                            dueTotalAmount: 3207.24
                            feesAmount: 0
                            intallments:
                              - number: 1
                                amount: 178.18
                          - duration: 24
                            effectiveAnnualPercentageRate: 8.9
                            nominalPercentageRate: 8.56
                            totalCost: 274.56
                            dueTotalAmount: 3274.56
                            feesAmount: 0
                            intallments:
                              - number: 1
                                amount: 136.44
        '400':
          description: Bad request.
          content:
            '*/*':
              schema:
                type: object
        '401':
          description: Unauthorized. You must first authenticate to get a valid token.
          content:
            '*/*':
              schema:
                type: object
        '403':
          description: Scope missing or insufficient permissions.
          content:
            application/json: {}
        default:
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaasExceptionHttpResponse'
              examples:
                Get Internal Server Error:
                  summary: Get Internal Server Error
                  description: Get Internal Server Error
                  value:
                    timestamp: '2022-07-28T22:25:51.000Z'
                    httpStatusCode: '500'
                    httpStatusMessage: Internal Server Error
                    errorMessage: Une erreur est survenue
                    requestMethod: POST
                    requestURI: /v1/_
  '/subscriptions/{creditSubscriptionId}':
    get:
      tags:
        - Subscriptions
      summary: Retrieve a specific E-Financing subscription
      description: |-
        You can use this API to get **all details** of a E-Financing
                subscription. You will have to provide **a E-Financing subscription Id**
                previously obtained as listed or initiated. 
      externalDocs:
        description: List of error codes.
        url: >-
          https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/api-reference/e-financing-api/e-financing-error-codes
      operationId: retrieveCreditSubscription
      parameters:
        - name: creditSubscriptionId
          in: path
          required: true
          schema:
            type: string
            description: The unique E-financement Subscription Id
            format: uuid
      responses:
        '200':
          description: Specific E-Financing subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreditSubscriptionDtoResponse'
        '401':
          description: Unauthorized. You must first authenticate to get a token.
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Missed scope or insufficient permission
          content:
            application/json: {}
        default:
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaasExceptionHttpResponse'
              examples:
                Get Internal Server Error:
                  summary: Get Internal Server Error
                  description: Get Internal Server Error
                  value:
                    timestamp: '2022-07-28T22:25:51.000Z'
                    httpStatusCode: '500'
                    httpStatusMessage: Internal Server Error
                    errorMessage: Une erreur est survenue
                    requestMethod: POST
                    requestURI: /v1/subscriptions
  /eligible-solutions:
    get:
      tags:
        - Eligibility
      summary: retrieve eligible E-financing solutions
      description: |-
        Retrieve eligible E-financing solutions given financed amount and buyer
                country.
                        As a result, you will a list of E-financing solutions codes with their related merchant kits.
                        A merchant kit will allow you to display E-financing visual name, label, description , logo and product terms to the customer.
                        An empty json object is returned if not eligible.
      operationId: getEligibleProductServices
      parameters:
        - name: buyerBillingCountry
          in: query
          required: true
          schema:
            type: string
            description: FR for France or DE for Germany. ISO 3166-1 alpha-2
            example: FR
        - name: financedAmount
          in: query
          required: true
          schema:
            type: number
            description: amount to be financed
            format: float
            example: 999.99
      responses:
        '200':
          description: The financed amount and country is eligible
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SolutionsResponseList'
        '401':
          description: Unauthorized. You must first authenticate to get a token.
          content:
            application/json:
              schema:
                type: object
        '403':
          description: Missed scope or insufficient permission
          content:
            application/json: {}
        default:
          description: Generic Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BaasExceptionHttpResponse'
components:
  schemas:
    Address:
      required:
        - cityName
        - countryCode
        - locationType
        - regionName
        - streetName
        - zipCode
      type: object
      properties:
        locationType:
          type: string
          description: >-
            Type of usage of the location BILLING_ADDRESS, MAIN_ADDRESS,
            DELIVERY_ADDRESS, PREVIOUS_MAIN_ADDRESS.
          enum:
            - BILLING_ADDRESS
            - MAIN_ADDRESS
            - DELIVERY_ADDRESS
            - PREVIOUS_MAIN_ADDRESS
        streetNumber:
          type: integer
          description: Numeric value of the street
          format: int32
          example: 147
        streetNumberSuffix:
          maxLength: 3
          minLength: 0
          type: string
          description: 'When necessary, suffix of the street number (10 B)'
          example: B
        streetName:
          type: string
          description: Name of the street
          example: main street
        streetNameComplement:
          type: string
          description: 'Complement, when necessary for the name of the street'
          example: block 47
        zipCode:
          type: string
          description: Zip code of address
          example: '92060'
        cityName:
          maxLength: 32
          minLength: 0
          type: string
          description: Name of the city
          example: Paris
        regionName:
          type: string
          description: Region/area where the city is located.
          example: Île-de-France
        countryCode:
          type: string
          description: Code of the country ISO 3166-1 alpha-2
          example: FR
    BasketDetails:
      required:
        - basketItems
      type: object
      properties:
        basketItems:
          type: array
          items:
            $ref: '#/components/schemas/BasketItem'
      description: >-
        Providing details about the products selected by the client in the
        basket from merchant portal such as main product,the total amount and
        quantity of the cart.
    BasketItem:
      required:
        - brandName
        - category
        - currencyCode
        - description
        - id
        - isFinanced
        - label
        - model
        - orderId
        - price
        - quantity
        - specifications
      type: object
      properties:
        id:
          type: string
          description: ID of a specific item within the basket
          example: M12345785513211
        quantity:
          type: integer
          description: Quantity of the item in the basket
          format: int32
          example: 1
        model:
          type: string
          description: Model of the item
          example: 5KPM5
        label:
          type: string
          description: Label of a specific item in the basket
          example: 'ROBOT PÂTISSIER À BOL RELEVABLE 4,8L - HEAVY DUTY 5KPM5'
        price:
          type: number
          description: Price of a specific item in the basket
          format: float
          example: 1199.99
        currencyCode:
          type: string
          description: Currency code applicable to prices based on ISO4217
          example: EUR
        orderId:
          type: string
          description: >-
            Id of the order of a specific item if the items are shipped
            separately and different order Ids are issued
          example: OD456742
        brandName:
          type: string
          description: Brand name of the item
          example: KitchenAid
        description:
          type: string
          description: Item commercial description
          example: >-
            Le robot pâtissier à bol relevable très résistant idéal pour mixer
            de grandes quantités d'ingrédients, équipé d'un bol en acier
            inoxydable amovible.
        specifications:
          type: string
          description: Item specifications
          example: 'Puissance (W) 315, Tension (V) 220-240, Fréquence (Hz) 50/60'
        category:
          type: string
          description: Category of the item
          example: Small appliance
        sku:
          type: string
          description: Item Stock Keeping Unit
          example: ZG011AQA
        isFinanced:
          type: boolean
          description: Flag the item if it is financed by the credit
          example: true
      description: >-
        Displaying the details of each product from shopping cart such as
        amount,quantity and product name.
    Buyer:
      required:
        - billingAddress
        - billingContact
        - contact
        - contactAddress
        - deliveryAddress
        - deliveryContact
      type: object
      properties:
        birthName:
          type: string
          description: Birth name
          example: Dupont
        birthDate:
          type: string
          description: Birth date
          example: '1975-02-01T00:00:00.000Z'
        birthCityName:
          type: string
          description: City of birth
          example: Montpellier
        birthCountryName:
          type: string
          description: 'Country of birth : Code of the country ISO 3166-1 alpha-2'
          example: FR
        deliveryMethod:
          type: string
          description: Delivery method
          example: Click & Collect
        lastDatePurchase:
          type: string
          description: Last purchase date
          example: '2020-02-01T00:00:00.000Z'
        vip:
          type: boolean
          description: VIP
          example: false
        contact:
          $ref: '#/components/schemas/Contact'
        contactAddress:
          $ref: '#/components/schemas/Address'
        billingContact:
          $ref: '#/components/schemas/Contact'
        billingAddress:
          $ref: '#/components/schemas/Address'
        deliveryContact:
          $ref: '#/components/schemas/Contact'
        deliveryAddress:
          $ref: '#/components/schemas/Address'
    Contact:
      required:
        - email
        - firstName
        - lastName
        - mobilePhoneNumber
      type: object
      properties:
        lastName:
          type: string
          description: Last name of the buyer (final customer)
          example: Dupont
        firstName:
          type: string
          description: First name of the buyer (final customer)
          example: Paul
        commonTitle:
          type: string
          description: Civility of the buyer (final customer)
          enum:
            - MR
            - MRS
        email:
          pattern: '^[a-zA-Z0-9_.+-]{1,100}@[a-zA-Z0-9-]{1,50}\.[a-zA-Z0-9.-]{1,50}$'
          type: string
          description: >-
            email adress of the buyer (final customer) with no international
            extension
          example: paul.dupont@mail.com
        mobilePhoneNumber:
          pattern: '^\+(?:[0-9] ?){6,14}[0-9]$'
          type: string
          description: Mobile number of the buyer (final customer)
          example: +33 1 23 45 67 89
        phoneNumber:
          pattern: '^$|\+(?:[0-9] ?){6,14}[0-9]$'
          type: string
          description: Phone number of the buyer (final customer)
          example: +33 1 23 45 67 89
        professionalTitle:
          type: string
          description: >-
            Professional title of the buyer from the list Professor, Dr., KC,
            Eur Ing, Chancellor etc…
          example: Professor
      description: >-
        Displaying the customer's personal contact details including first name,
        last name and mobile phone.
    InitiateCreditSubscriptionRequest:
      required:
        - basketDetails
        - buyers
        - financedAmount
        - merchantBasketId
        - merchantBuyerId
        - merchantGlobalOrderId
        - merchantUrls
        - solutionCode
      type: object
      properties:
        solutionCode:
          type: string
          description: ID of the BaaS product used
          example: SCFRSP-3XPS
        merchantBasketId:
          type: string
          description: >-
            ID of the basket of the current transaction, as given by the
            merchant (third party)
          example: 647aeb24-a89c-11ed-afa1-0242ac120002
        merchantGlobalOrderId:
          type: string
          description: >-
            ID of the order as a whole - as long as the items are not dispatched
            separately, with different order IDs (cf. basket table)
          example: 3e46d670-aca7-11ed-afa1-0242ac120002
        merchantBuyerId:
          type: string
          description: >-
            ID of the buyer (final customer), as given by the merchant (third
            party)
          example: 44226c6c-aca7-11ed-afa1-0242ac120002
        financedAmount:
          type: number
          description: >-
            Total amount within the basket which is financed by credit - can
            represent the whole basket if every item is financed
          format: float
          example: 119.9
        merchantUrls:
          $ref: '#/components/schemas/MerchantUrls'
        buyers:
          maxItems: 1
          minItems: 0
          type: array
          description: List of buyer
          items:
            $ref: '#/components/schemas/Buyer'
        basketDetails:
          $ref: '#/components/schemas/BasketDetails'
      description: Credit Subscription Request
    MerchantUrls:
      required:
        - confirmation
      type: object
      properties:
        confirmation:
          type: string
          description: >-
            URL, sent by the merchant at the start of the work flow, to send
            back the buyer to his website upon finishing his credit work flow
          format: uri
          example: 'https://mymerchand.domain/uri'
    InitiateCreditSubscriptionResponse:
      required:
        - id
      type: object
      properties:
        id:
          type: string
          description: The unique Credit Subscription Id
          format: uuid
          example: 1b8cb15b-fbd3-4a65-9a39-ab81f6307b81
        redirect:
          $ref: '#/components/schemas/Redirect'
    Redirect:
      type: object
      properties:
        type:
          type: string
          enum:
            - url
            - page
        value:
          type: string
    BaasExceptionHttpResponse:
      type: object
      properties:
        timestamp:
          type: string
          description: Timestamp of the error
          format: date-time
          example: '2023-01-29T10:05:38.429Z'
        httpStatusCode:
          type: integer
          description: 'HTTP status code (404, 400, 500...)'
          format: int32
          example: 400
        httpStatusMessage:
          type: string
          description: >-
            HTTP status message ("Not Found", "Bad Request", "Internal Server
            Error"...)
          example: Bad Request
        errorCode:
          type: string
          description: >-
            The applicative error code. It is a machine readable code. Used when
            BAD_REQUEST error to provide details about the error.
          example: INVALID_EMAIL
        errorMessage:
          type: string
          description: >-
            The applicative error message. It is a human readable English
            message.
          example: The email address is not valid !
        errors:
          type: array
          description: 'List of { error code, error message }.'
          items:
            $ref: '#/components/schemas/ErrorCodeAndMessage'
        requestMethod:
          type: string
          description: >-
            HTTP method used to make the request ("GET", "POST", "PUT",
            "DELETE"...)
          example: POST
        requestURI:
          type: string
          description: HTTP URI used to make the request
          example: /v1/user-account/users
      description: Generic HTTP Error Response
    ErrorCodeAndMessage:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      description: 'List of { error code, error message }.'
    ConfirmReturnRequest:
      required:
        - isReturned
      type: object
      properties:
        isReturned:
          type: boolean
          description: Status of the return
          example: true
      description: >-
        Request indicating whether or not the customer returned the items to the
        merchant
    ConfirmDeliveryRequest:
      required:
        - isDelivered
      type: object
      properties:
        isDelivered:
          type: boolean
          description: Refers to the request to use to confirm the delivery of the items
          example: true
        trackingNumber:
          maxLength: 100
          minLength: 1
          type: string
          description: The delivery identifier
          example: '12349875641919191000'
        operator:
          type: string
          description: The delivery company
          example: DHL
          enum:
            - UPS
            - DHL
            - CHRONOPOST
            - LA_POSTE
            - DPD
            - RELAIS_COLIS
            - MONDIAL_RELAY
            - FEDEX
            - GLS
            - UNKNOWN
    CreditCancellationResponse:
      type: object
      properties:
        financedAmount:
          type: number
          description: >-
            New financedAmount after updating. Calculation financedAmount
            deducted with the cancelledAmount.
          format: float
          example: 119.9
        status:
          type: string
          description: >-
            ACCEPTED if the cancellation is accepted. Returned by producer and
            Franfinance. For Hanseatic, a first returned status is Requested,
            and after the final response the status is Approved.
          example: ACCEPTED
          enum:
            - INITIALIZED
            - REQUESTED
            - PRE_ACCEPTED
            - ACCEPTED
            - REJECTED
            - ABORTED
            - CANCELLED
            - REQUEST_CANCELLATION
            - REQUEST_PART_CANCELLATION
            - CANCEL_FULL_ACCEPTED
            - CANCEL_FULL_REJECTED
            - CANCEL_PART_ACCEPTED
            - CANCEL_PART_REJECTED
    CancellationContact:
      type: object
      properties:
        lastName:
          type: string
          description: Last name of the buyer (final customer)
          example: Dupont
        firstName:
          type: string
          description: First name of the buyer (final customer)
          example: Paul
        email:
          type: string
          description: >-
            Email adress of the buyer (final customer) with no international
            extension
          example: paul.dupont@mail.com
        phoneNumber:
          type: string
          description: >-
            Phone number of the buyer (final customer) with no international
            extension
          example: 09 55 55 66 66
    CreditCancellationDTO:
      type: object
      properties:
        cancelledAmount:
          type: number
          description: >-
            Amount cancelled asked. It will stored on the event table and
            deducted from the initial financed amount.
          format: float
          example: 119.9
        cancelledItem:
          type: string
          description: ID of a specific item within the basket
          example: M12345785513211
        cancellationReason:
          type: string
          description: The reason why the credit is cancelled in the transacation
          example: The item is too big for my kitchen
        cancellationContact:
          $ref: '#/components/schemas/CancellationContact'
    SolutionSimulationRequest:
      required:
        - buyerBillingCountry
        - financedAmount
      type: object
      properties:
        financedAmount:
          type: number
          description: Amount to be financed.
          format: float
          example: 3943.36
        buyerBillingCountry:
          type: string
          description: Country of the buyer (FR for France or DE for Germany).
          example: FR
          enum:
            - FR
            - DE
        solutionCodes:
          type: array
          description: >-
            List of codes used for identifying all or part of the eligible
            e-financing solutions to be simulated. By default, all eligible
            e-financing solutions will be simulated.
          example: 'List [ "SCFRSP-3XTS" ]'
          items:
            type: string
            description: >-
              List of codes used for identifying all or part of the eligible
              e-financing solutions to be simulated. By default, all eligible
              e-financing solutions will be simulated.
            example: 'List [ "SCFRSP-3XTS" ]'
      description: >-
        Request body represents the data that will be used to simulate the
        eligible e-financing solutions.
    Installment:
      required:
        - amount
        - number
      type: object
      properties:
        number:
          type: integer
          description: Installment number.
          format: int32
          example: 1
        amount:
          type: number
          description: Monthly installment amount.
          format: float
          example: 325.97
      description: |-
        Installment details.
         For solutions (French long credit) that the code is staring with SCFRLT, installment list returns the amount of only one installment.
         For solutions of type split payments (3X, 4X ...), all installments will be returned.)
    Simulation:
      required:
        - dueTotalAmount
        - duration
        - effectiveAnnualPercentageRate
        - feesAmount
        - installments
        - nominalPercentageRate
        - totalCost
      type: object
      properties:
        duration:
          type: integer
          description: Number of installments.
          format: int32
          example: 3
        effectiveAnnualPercentageRate:
          type: number
          description: Annual percentage rate of charge (APRC). French abbreviation (TAEG).
          format: float
          example: 3.6
        nominalPercentageRate:
          type: number
          description: Nominal percentage rate.
          format: float
          example: 3.1
        totalCost:
          type: number
          description: Total financing cost including fees and interest charges.
          format: float
          example: 4288.7
        dueTotalAmount:
          type: number
          description: >-
            The total amount to be paid. The sum of financedAmount and the
            totalCost.
          format: float
          example: 56.5
        feesAmount:
          type: number
          description: Amount of additional fees.
          format: float
          example: 3943.36
        installments:
          type: array
          description: List of installment details.
          items:
            $ref: '#/components/schemas/Installment'
      description: Simulation result for the e-financing solution code and its duration.
    SolutionSimulationItem:
      required:
        - simulations
        - solutionCode
      type: object
      properties:
        solutionCode:
          type: string
          description: Code used for identifying the eligible e-financing solution.
          example: SCFRSP-3XTS
        simulations:
          type: array
          description: >-
            List of simulation result for a given e-financing solution code by
            durations.
          items:
            $ref: '#/components/schemas/Simulation'
      description: Simulation result based on a specific solution code.
    SolutionSimulationResponse:
      required:
        - buyerBillingCountry
        - financedAmount
        - solutionSimulations
      type: object
      properties:
        financedAmount:
          type: number
          description: Amount to be financed.
          format: float
          example: 3943.36
        buyerBillingCountry:
          type: string
          description: Country of the buyer (FR for France or DE for Germany).
          example: FR
          enum:
            - FR
            - DE
        solutionSimulations:
          type: array
          description: List of simulation results grouped by solutionCode.
          items:
            $ref: '#/components/schemas/SolutionSimulationItem'
      description: >-
        The result of the simulation of eligible financial solutions for a given
        amount and solution codes.
    CreditSubscriptionDto:
      required:
        - buyerFinancedAmount
        - cancellationAlreadyMade
        - consolidatedStatus
        - creditSubscriptionId
        - lastUpdateTimestamp
        - marketTypeCode
        - merchantBasketId
        - merchantGlobalOrderId
        - registrationTimestamp
        - solutionCode
      type: object
      properties:
        creditSubscriptionId:
          type: string
          description: The unique Credit Subscription Id
          format: uuid
        registrationTimestamp:
          type: string
          format: date-time
          example: '2024-04-22T10:00:19.077Z'
        lastUpdateTimestamp:
          type: string
          format: date-time
          example: '2024-04-22T10:00:19.077Z'
        solutionCode:
          type: string
          description: ID of the BaaS product used
          example: SCFRSP-4XPS
        marketTypeCode:
          type: string
          description: ID of the market in which the product is valid
          example: FR
        implementationCode:
          type: string
          description: >-
            anciennement installments - installment contains ideally the
            installment of the credit subscription. The value is the number of
            month selected by the final client for his credit
          example: 3X
        merchantBasketId:
          type: string
          description: >-
            ID of the basket of the current transaction, as given by the
            merchant (third party)
          example: 061be358-acb1-11ed-afa1-0242ac120002
        merchantGlobalOrderId:
          type: string
          description: >-
            ID of the order as a whole - as long as the items are not dispatched
            separately, with different order IDs (cf. basket table)
          example: 0c34ab62-acb1-11ed-afa1-0242ac120002
        buyerFinancedAmount:
          type: number
          description: >-
            Total amount in the basket which is financed by credit - can
            represent the whole basket if every item is financed
          format: float
          example: 1199.99
        consolidatedStatus:
          type: string
          description: Current status of the buyer (final customer) credit subscription
          enum:
            - INITIALIZED
            - REQUESTED
            - PRE_ACCEPTED
            - ACCEPTED
            - REJECTED
            - ABORTED
            - CANCELLED
        cancellationStatus:
          type: string
          enum:
            - REQUEST_FOR_PARTIAL_CANCELLATION
            - REQUEST_FOR_CANCELLATION
            - CANCELLATION_ACCEPTED
            - CANCELLATION_REJECTED
            - PARTIAL_CANCELLATION_ACCEPTED
            - PARTIAL_CANCELLATION_REJECTED
        cancellationAlreadyMade:
          type: boolean
          description: >-
            This field indicates is a demand of cancellation was already made or
            not. The value is True only is the demand of cancellation partial or
            Total has been accepted.
          example: false
        consolidatedSubstatus:
          type: string
          description: >-
            Substatus gives details about a consolidated status of the credit
            subscription.
          example: SUBSCRIPTION APPROVED BY PRODUCER
        isReturned:
          type: boolean
          description: Status of the return
          example: true
        isDelivered:
          type: boolean
          description: Status of the delivery
          example: true
      description: List of Subscription
    PaginationCreditSubscriptionsDtoResponse:
      required:
        - subscriptions
        - totalItemCount
      type: object
      properties:
        totalItemCount:
          type: integer
          format: int32
          example: 1
        subscriptions:
          type: array
          description: List of Subscription
          items:
            $ref: '#/components/schemas/CreditSubscriptionDto'
    CreditSubscriptionDtoResponse:
      required:
        - basketDetails
        - buyer
        - cancellationAlreadyMade
        - consolidatedStatus
        - creditSubscriptionId
        - familyCode
        - financedAmount
        - lastUpdateTimestamp
        - marketTypeCode
        - merchantBasketId
        - merchantBuyerId
        - merchantGlobalOrderId
        - registrationTimestamp
        - solutionCode
      type: object
      properties:
        creditSubscriptionId:
          type: string
          description: The unique Credit Subscription Id
          format: uuid
        registrationTimestamp:
          type: string
          format: date-time
          example: '2024-04-22T10:00:19.077Z'
        lastUpdateTimestamp:
          type: string
          format: date-time
          example: '2024-04-22T10:00:19.077Z'
        solutionCode:
          type: string
          description: ID of the BaaS product used
          example: SCFRSP-4XPS
        familyCode:
          type: string
          description: Smart Credit
          example: SC
        marketTypeCode:
          type: string
          description: ID of the market in which the product is valid
          example: FR
        implementationCode:
          type: string
          description: >-
            Contains ideally the number of installments of the credit
            subscription. The value is the number of months selected by the
            final client for his credit.
          example: 3X
        merchantBasketId:
          type: string
          description: >-
            ID of the basket of the current transaction, as given by the
            merchant (third party)
          example: 647aeb24-a89c-11ed-afa1-0242ac120002
        merchantGlobalOrderId:
          type: string
          description: >-
            ID of the order as a whole - as long as the items are not dispatched
            separately, with different orders ID (cf. basket table)
          example: 3e46d670-aca7-11ed-afa1-0242ac120002
        merchantBuyerId:
          type: string
          description: >-
            ID of the buyer (final customer), as given by the merchant (third
            party)
          example: 44226c6c-aca7-11ed-afa1-0242ac120002
        financedAmount:
          type: number
          description: >-
            Total amount within the basket which is financed by credit - can
            represent the whole basket if every item is financed
          format: float
          example: 119.9
        consolidatedStatus:
          type: string
          description: Current status of the buyer (final customer) credit subscription
          enum:
            - INITIALIZED
            - REQUESTED
            - PRE_ACCEPTED
            - ACCEPTED
            - REJECTED
            - ABORTED
            - CANCELLED
        cancellationStatus:
          type: string
          enum:
            - REQUEST_FOR_PARTIAL_CANCELLATION
            - REQUEST_FOR_CANCELLATION
            - CANCELLATION_ACCEPTED
            - CANCELLATION_REJECTED
            - PARTIAL_CANCELLATION_ACCEPTED
            - PARTIAL_CANCELLATION_REJECTED
        cancellationAlreadyMade:
          type: boolean
          description: >-
            This field indicates is a demand of cancellation was already made or
            not. The value is True only is the demand of cancellation partial or
            Total has been accepted.
          example: false
        buyer:
          $ref: '#/components/schemas/Buyer'
        basketDetails:
          type: string
          description: >-
            Providing details about the products selected by the client in the
            basket from merchant portal such as main product,the total amount
            and quantity of the cart.
          example: FR
        consolidatedSubstatus:
          type: string
          description: >-
            Substatus gives details about a consolidated status of the credit
            subscription.
          example: SUBSCRIPTION APPROVED BY PRODUCER
        isReturned:
          type: boolean
          description: status of the return
          example: true
        isDelivered:
          type: boolean
          description: status of the delivery
          example: true
    CommunicationKit:
      required:
        - solutionCode
        - visualAdditionalInformation
        - visualInformationIcon
      type: object
      properties:
        solutionCode:
          type: string
          description: solution code to which the communication kit belongs
          example: SCFRSP-3XTS
        visualTitle:
          type: string
          description: >-
            relates to Merchant's kit. Item label to display on the merchant
            webSite
          example: Payez en 3 ou 4 fois
        visualDescription:
          type: string
          description: Description of the insert on the merchant website - optional
          example: Baas is great
        visualInformationIcon:
          type: string
          description: 'Icon integrated in the insert, which allows access to the pop-in'
          example: XXX/XXX.ico (url icon)
        visualAdditionalInformation:
          type: string
          description: >-
            Additional information to which the final consumer can access via
            the information icon
          example: xxx
        visualLegalText:
          type: string
          description: Legal text to be displayed below the product description
          example: xxx
        visualTableImage:
          type: string
          description: >-
            Static table image representing the different installments for an
            example of split payment
          example: 'https://merchant.kit/uri/table.png'
        visualLogo:
          type: string
          description: BaaS service logo
          example: 'https://merchant.kit/uri/productTerms.ico'
        visualInformationNoticeURL:
          type: string
          description: Link to Moonshot information notice (pdf)
          example: 'https://merchant.kit/uri/productTerms.pdf'
        visualProductTermsURL:
          type: string
          description: Link to the moonshot product file pdf
          example: 'https://merchant.kit/uri/productTerms.pdf'
      description: Communication Kit
    ProductsAndServicesResponse:
      required:
        - communicationKit
        - conditions
        - familyCode
        - marketCode
        - solutionCode
      type: object
      properties:
        solutionCode:
          type: string
          description: Code used for identify the product
          example: SCFRSP-3XTS
        familyCode:
          type: string
          description: Credit or Insurance (in our case is most used for Credit)
          example: SC
        marketCode:
          type: string
          description: Code used for identify the country market
          example: FR for France or DE for Germany
        conditions:
          type: string
          description: 'with or without fees, or rate for long term credit'
          example: PS
        communicationKit:
          $ref: '#/components/schemas/CommunicationKit'
      description: Eligible product services process object
    SolutionsResponseList:
      type: object
      properties:
        solutions:
          type: array
          items:
            $ref: '#/components/schemas/ProductsAndServicesResponse'
  securitySchemes:
    oauth-flows:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: >-
            https://api.scalexpert.uatc.societegenerale.com/baas/uatc/auth-server/api/v1/oauth2/token
          scopes:
            'e-financing:rw': ''
externalDocs:
  description: Dev docs
  url: >-
    https://docs.scalexpert.societegenerale.com/apidocs/3mLlrPx3sPtekcQvEEUg/developers-docs/get-started
security:
  - oauth-flows:
      - 'e-financing:rw'
x-sg-configuration:
  gateways:
    - name: baas-open-gateway
      description: To expose Open APIs to BAAS partners
      url: 'https://api.scalexpert.uatc.societegenerale.com/baas/uatc'
